### ISSUE TITLE
iRedAdmin "Internal Server Error" after upgrading Ubuntu 18.04 LTS to Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by xpresserversllc** [iredmail/iRedMail#123]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.4.0
- Deployed with iRedMail Easy or the downloadable installer? Downloadable Installer
- Linux/BSD distribution name and version: Ubuntu 20.04 LTS
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? No
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

```
root@iredmail:/var/log# service iredadmin status
● iredadmin.service - iRedAdmin daemon service
     Loaded: loaded (/lib/systemd/system/iredadmin.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-07-10 13:45:03 UTC; 8min ago
    Process: 4291 ExecStartPre=/bin/mkdir -p /var/run/iredadmin (code=exited, status=0/SUCCESS)
    Process: 4308 ExecStartPre=/bin/chown iredadmin:iredadmin /var/run/iredadmin (code=exited, status=0/SUCCESS)
    Process: 4312 ExecStartPre=/bin/chmod 0755 /var/run/iredadmin (code=exited, status=0/SUCCESS)
   Main PID: 4313 (uwsgi)
      Tasks: 6 (limit: 9432)
     Memory: 28.3M
     CGroup: /system.slice/iredadmin.service
             ├─4313 /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid
             ├─4316 /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid
             ├─4317 /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid
             ├─4318 /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid
             ├─4319 /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid
             └─4320 /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid

Jul 10 13:45:11 iredmail iredadmin[4313]: [xx.xx.xx.xx] GET /iredadmin/dashboard 500 104 "-"
Jul 10 13:53:19 iredmail iredadmin[4313]: Traceback (most recent call last):
Jul 10 13:53:19 iredmail iredadmin[4313]:   File "/opt/www/iRedAdmin-1.3/iredadmin.py", line 8, in <module>
Jul 10 13:53:19 iredmail iredadmin[4313]:     from libs import iredbase
Jul 10 13:53:19 iredmail iredadmin[4313]:   File "/opt/www/iRedAdmin-1.3/libs/iredbase.py", line 5, in <module>
Jul 10 13:53:19 iredmail iredadmin[4313]:     import web
Jul 10 13:53:19 iredmail iredadmin[4313]: ModuleNotFoundError: No module named 'web'
Jul 10 13:53:19 iredmail iredadmin[4313]: unable to load app 0 (mountpoint='iredmail.xpresservers.pk|/iredadmin') (callable not found or import error)
Jul 10 13:53:19 iredmail iredadmin[4313]: --- no python application found, check your startup logs for errors ---
Jul 10 13:53:19 iredmail iredadmin[4313]: [xx.xx.xx.xx] GET /iredadmin/dashboard 500 104 "-"
```

**Comment by iredmail** [comment]
Run commands below to fix it:

```
pip3 install web.py
service iredadmin restart
```

I suggest re-upgrade iRedAdmin and let its upgrade script to fix potential issues for you.

FYI: https://docs.iredmail.org/upgrade.ubuntu.18.04-20.04.html
