### ISSUE TITLE
/iRedAdmin-Pro-SQL-5.5 Internal error application.py, line 277, in process return self.handle()

### ISSUE THREAD

**Issue by bolinches** [iredmail/iRedMail#255]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.6.8
- Deployed with iRedMail Easy or the downloadable installer? installer
- Linux/BSD distribution name and version: FreeBSD 13.3
- Store mail accounts in which backend (LDAP/MySQL/PGSQL): MySQL
- Web server (Apache or Nginx):
- Manage mail accounts with iRedAdmin-Pro? Yes
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue.

Accessing iredadmin PRO 5.5 (5.4 too) and the non Pro/Paid version I get the following:

GET https://MYMAILSERVER_FQDN/iredadmin/

Traceback (most recent call last):
  File "/usr/local/www/iRedAdmin-Pro-SQL-5.5/web/application.py", line 277, in process
    return self.handle()
           ^^^^^^^^^^^^^
  File "/usr/local/www/iRedAdmin-Pro-SQL-5.5/web/application.py", line 268, in handle
    return self._delegate(fn, self.fvars, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/iRedAdmin-Pro-SQL-5.5/web/application.py", line 506, in _delegate
    mod = __import__(mod, None, None, [""])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/iRedAdmin-Pro-SQL-5.5/controllers/sql/basic.py", line 14, in <module>
    from libs.sqllib import domain as sql_lib_domain
  File "/usr/local/www/iRedAdmin-Pro-SQL-5.5/libs/sqllib/domain.py", line 15, in <module>
    from libs.panel import domain_ownership
  File "/usr/local/www/iRedAdmin-Pro-SQL-5.5/libs/panel/domain_ownership.py", line 5, in <module>
    from dns import resolver
  File "/usr/local/lib/python3.11/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/usr/local/lib/python3.11/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/usr/local/lib/python3.11/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/usr/local/lib/python3.11/site-packages/dns/asyncquery.py", line 32, in <module>
    import dns.quic
  File "/usr/local/lib/python3.11/site-packages/dns/quic/__init__.py", line 7, in <module>
    import aioquic.quic.configuration  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioquic/quic/configuration.py", line 6, in <module>
    from ..tls import (
  File "/usr/local/lib/python3.11/site-packages/aioquic/tls.py", line 25, in <module>
    import service_identity
  File "/usr/local/lib/python3.11/site-packages/service_identity/__init__.py", line 6, in <module>
    from . import cryptography, hazmat, pyopenssl
  File "/usr/local/lib/python3.11/site-packages/service_identity/cryptography.py", line 11, in <module>
    from cryptography.x509 import (
  File "/usr/local/lib/python3.11/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency, verification
  File "/usr/local/lib/python3.11/site-packages/cryptography/x509/certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: PyO3 modules do not yet support subinterpreters, see https://github.com/PyO3/pyo3/issues/576

**Comment by iredmail** [comment]
Seems a bug of Python module `cryptography`. Does it work if you downgrade it to version `40.0.2`?

```
pip install -U cryptography==40.0.2
```

**Comment by bolinches** [comment]
Hi

Yes that fixed it. Thanks
