### ISSUE TITLE
iRedAdmin report "Internal server error" after clean install on ubuntu server 20.04

### ISSUE THREAD

**Issue by franky920920** [iredmail/iRedMail#85]
REQUIRED BASIC INFO OF YOUR IREDMAIL SERVER:

- iRedMail version (check /etc/iredmail-release): 1.3.1 OpenLDAP edition
- Deployed with iRedMail Easy or the downloadable installer? downloadable installer
- Linux/BSD distribution name and version: ubuntu server 20.04
- Store mail accounts in which backend (LDAP/MySQL/PGSQL):  LDAP
- Web server (Apache or Nginx): Nginx
- Manage mail accounts with iRedAdmin-Pro? 
- [IMPORTANT] Related original log or error message is required if you're experiencing an issue. Internal server error

I just install the iRedMail on my new ubuntu server. All mail functions are ok but the iRedAdmin show an "Internal server error" 
![image](https://user-images.githubusercontent.com/11349917/92990567-13482b00-f510-11ea-9657-a1addde6bcff.png)

And this issue #63 doesn't fix this.

Please help with this. If further information is needed, just ask for it and I will provide asap. Thanks.

**Comment by iredmail** [comment]
Any related error in /var/log/syslog?

**Comment by franky920920** [comment]
> Any related error in /var/log/syslog?

cat: /var/log/syslog: No such file or directory

**Comment by iredmail** [comment]
Please restart “rsyslog” service first, it should creates /var/log/syslog for you. Then access iredadmin again to trigger the issue, and check /var/log/syslog again to get related error.

**Comment by franky920920** [comment]
> Please restart “rsyslog” service first, it should creates /var/log/syslog for you. Then access iredadmin again to trigger the issue, and check /var/log/syslog again to get related error.

root@mail:/var/log# service rsyslog restart
Failed to restart rsyslog.service: Unit rsyslog.service not found.

It appears the service do not exists

**Comment by iredmail** [comment]
“rsyslog” is standard syslog server on Linux, I’m not sure why your Ubuntu 20.04 doesn’t have it. 

Anyway, try this instead:

cd /opt/www/iredadmin/
python2 iredadmin.py

It will start a web server listening on port 8080, please run command below on another console:

curl -k https://localhost:8080

What’s the error on console?

**Comment by franky920920** [comment]
> “rsyslog” is standard syslog server on Linux, I’m not sure why your Ubuntu 20.04 doesn’t have it.
> 
> Anyway, try this instead:
> 
> cd /opt/www/iredadmin/
> python2 iredadmin.py
> 
> It will start a web server listening on port 8080, please run command below on another console:
> 
> curl -k https://localhost:8080
> 
> What’s the error on console?

I've found out cause this is a minimized version of ubuntu server so the service rsyslog isn't install.
I've now unminimizing that server.
Please wait until the unminimizing process finished and I will do the python2 iredadmin.py.
Thanks.

**Comment by franky920920** [comment]
The result for the command python2 iredadmin.py
```
root@mail:/opt/www/iredadmin# python2 iredadmin.py
Traceback (most recent call last):
  File "iredadmin.py", line 9, in <module>
    from libs import iredbase
  File "/opt/www/iRedAdmin-1.0/libs/iredbase.py", line 43, in <module>
    pw=settings.iredadmin_db_password,
  File "/usr/local/lib/python2.7/dist-packages/web/db.py", line 1489, in database
    return _databases[dbn](**params)
  File "/usr/local/lib/python2.7/dist-packages/web/db.py", line 1253, in __init__
    db = import_driver(mysql_drivers, preferred=keywords.pop("driver", None))
  File "/usr/local/lib/python2.7/dist-packages/web/db.py", line 1299, in import_driver
    raise ImportError("Unable to import " + " or ".join(drivers))
ImportError: Unable to import MySQLdb or pymysql or mysql.connector
```

and the python script exit.

The curl command return: `curl: (7) Failed to connect to localhost port 8080: Connection refused`

**Comment by franky920920** [comment]
Hi, an update shows the issue can now be closed.
According to the message from python2 iredadmin.py, I've run the command `sudo pip install pymysql` and the problem is now solved. I'll close this issue now. Thanks for the instant reply for the issue.

Have a nice day.

**Comment by amirZand99** [comment]
python3 iredadmin.py 
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "/home/amir/iRedAdmin/web/application.py", line 275, in process
    return p(lambda: process(processors))
  File "/home/amir/iRedAdmin/web/session.py", line 96, in _processor
    self._cleanup()
  File "/home/amir/iRedAdmin/web/session.py", line 197, in _cleanup
    self.store.cleanup(timeout)
  File "/home/amir/iRedAdmin/web/session.py", line 373, in cleanup
    self.db.delete(self.table, where="$last_allowed_time > atime", vars=locals())
  File "/home/amir/iRedAdmin/web/db.py", line 1154, in delete
    db_cursor = self._db_cursor()
  File "/home/amir/iRedAdmin/web/db.py", line 723, in _db_cursor
    return self.ctx.db.cursor()
  File "/home/amir/iRedAdmin/web/db.py", line 661, in _getctx
    self._load_context(self._ctx)
  File "/home/amir/iRedAdmin/web/db.py", line 673, in _load_context
    ctx.db = self._connect(self.keywords)
  File "/home/amir/iRedAdmin/web/db.py", line 701, in _connect
    return self.db_module.connect(**keywords)
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'iredadmin'@'localhost' (using password: YES)")

127.0.0.1:47302 - - [09/Dec/2023 11:53:54] "HTTP/1.1 GET /" - 500 Internal Server Error
Traceback (most recent call last):
  File "/home/amir/iRedAdmin/web/application.py", line 275, in process
    return p(lambda: process(processors))
  File "/home/amir/iRedAdmin/web/session.py", line 96, in _processor
    self._cleanup()
  File "/home/amir/iRedAdmin/web/session.py", line 197, in _cleanup
    self.store.cleanup(timeout)
  File "/home/amir/iRedAdmin/web/session.py", line 373, in cleanup
    self.db.delete(self.table, where="$last_allowed_time > atime", vars=locals())
  File "/home/amir/iRedAdmin/web/db.py", line 1154, in delete
    db_cursor = self._db_cursor()
  File "/home/amir/iRedAdmin/web/db.py", line 723, in _db_cursor
    return self.ctx.db.cursor()
  File "/home/amir/iRedAdmin/web/db.py", line 661, in _getctx
    self._load_context(self._ctx)
  File "/home/amir/iRedAdmin/web/db.py", line 673, in _load_context
    ctx.db = self._connect(self.keywords)
  File "/home/amir/iRedAdmin/web/db.py", line 701, in _connect
    return self.db_module.connect(**keywords)
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/amir/iRedAdmin/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'iredadmin'@'localhost' (using password: YES)")

127.0.0.1:47302 - - [09/Dec/2023 11:53:54] "HTTP/1.1 GET /favicon.ico" - 500 Internal Server Error
